---
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Create virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ azure_resourcegroup_name }}"
        name: vNet
        address_prefixes: "10.0.0.0/22"

    - name: Add subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ azure_resourcegroup_name }}"
        name: subnet
        address_prefix: "10.0.0.0/23"
        virtual_network: vNet

    - name: Create public IP address
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ azure_resourcegroup_name }}"
        allocation_method: Static
        name: pip
      register: output_ip_address

    - name: Output public IP
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"

    - name: Create Network Security Group
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ azure_resourcegroup_name }}"
        name: networkSecurityGroup
        rules:
          - name: 'allow_rdp'
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
          - name: 'allow_web_traffic'
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound
          - name: 'allow_powershell_remoting'
            protocol: Tcp
            destination_port_range:
              - 5985
              - 5986
            access: Allow
            priority: 1003
            direction: Inbound

    - name: Create a network interface
      azure.azcollection.azure_rm_networkinterface:
        name: nic
        resource_group: "{{ azure_resourcegroup_name }}"
        virtual_network: vNet
        subnet_name: subnet
        security_group: networkSecurityGroup
        ip_configurations:
          - name: default
            public_ip_address_name: pip
            primary: True
            
    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{ azure_resourcegroup_name }}"
        name: "{{ vm_name }}_NIC"
        virtual_network: vNet
        subnet: subnet
        security_group: networkSecurityGroup
      register: vm_nic

    - name: Create VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ azure_resourcegroup_name }}"
        name: "{{ vm_name }}"
        vm_size: Standard_DS1_v2
        admin_username: azureuser
        admin_password: "{{ password }}"
        network_interfaces: "{{ vm_name }}_NIC"
        os_type: Windows
        tags:
          "os_type": "Windows"
          "env": "{{ environment }}"
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2019-Datacenter
          version: latest
      no_log: false

    - name: Create VM script extension to enable HTTPS WinRM listener
      azure.azcollection.azure_rm_virtualmachineextension:
        name: winrm-extension
        resource_group: "{{ azure_resourcegroup_name }}"
        virtual_machine_name: "{{ vm_name }}"
        publisher: Microsoft.Compute
        virtual_machine_extension_type: CustomScriptExtension
        type_handler_version: '1.9'
        settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
        auto_upgrade_minor_version: true

    - name: Get facts for one Public IP
      azure.azcollection.azure_rm_publicipaddress_info:
        resource_group: "{{ azure_resourcegroup_name }}"
        name: pip
      register: publicipaddresses

    - name: set public ip address fact
      set_fact: publicipaddress="{{ publicipaddresses | json_query('publicipaddresses[0].ip_address')}}"

    - name: wait for the WinRM port to come online
      wait_for:
        port: 5986
        host: '{{ publicipaddress }}'
        timeout: 600
