---
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Remove a VM and all resources that were autocreated
    azure.azcollection.azure_rm_virtualmachine:
      resource_group: "{{ azure_resourcegroup_name }}"
      name: "{{ vm_name }}"
      remove_on_absent: all_autocreated
      state: absent

  - name: Remove public IP address
    azure.azcollection.azure_rm_publicipaddress:
      resource_group: "{{ azure_resourcegroup_name }}"
      name: "{{ public_ip }}"
      state: absent

  - name: Delete network interface
    azure.azcollection.azure_rm_networkinterface:
      resource_group: "{{ azure_resourcegroup_name }}"
      name: "{{ vm_name }}_NIC"
      state: absent

  - name: Remove storage account, if it exists
    azure.azcollection.azure_rm_storageaccount:
      resource_group: "{{ azure_resourcegroup_name }}"
      name: "{{ storage_account }}"
      state: absent


