---
- hosts: all
  vars:
    ansible_user: azureuser
    password: "{{ password }}"
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
  - name: Test connection
    win_ping:
