---
- name: Updating Windows
  hosts: all
  serial: "{{ serial }}"
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Install all critical and security updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
        state: installed
        
    - name: reboot host if required
      win_reboot:
        reboot_timeout: 3600
      
