---
- name: Updating Windows
  hosts: all
  serial: "{{ serial }}"
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:  
    - name: reboot host if required
      win_reboot:
        reboot_timeout: 3600
