---
- name: ensure .NET Framework 4.8 requirement is satisfied for Chocolatey CLI v2.0.0+
  block:
  - name: install Chocolatey CLI v1.4.0
    win_chocolatey:
      name: 'chocolatey'
      state: present
      version: '1.4.0'
      
- name: Install Packages using Chocolatey
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ choco_packages }}" 
    state: "{{ choco_packages_state }}"
