---
- name: Create report path if it doesn't exist already
  ansible.windows.win_file:
    path: "{{ source }}"
    state: directory

- name: Create file if it doesn't exist already
  ansible.windows.win_file:
    path: "{{ source }}/{{ file }}"
    state: touch

- name: Add a line to a file
  community.windows.win_lineinfile:
    path: "{{ source }}/{{ file }}"
    line: "{{ line }}"

- name: Create backup with RoboCopy
  community.windows.win_robocopy:
    src: "{{ source }}"
    dest: "{{ destination }}"
